### ISSUE TITLE
add persist for FireDM

### ISSUE THREAD

**Issue by candrapersada** [yuuki76/kris-scoop#1]
add persist for update FireDM from scoop without missing FireDM settings

`setting.cfg`
`thumbnails.dat`
`user_themes.cfg`

**Comment by krisfail** [comment]
@candrapersada 
I apologize for abandoning this repository for so long.
I completely forgot to maintain this repository.

**Comment by krisfail** [comment]
I just noticed that FireDM was gone.
Again, I apologize for neglecting @candrapersada and for not being able to capture the results of the work.
